CREATE TABLE TB_MOVIE
(
     CODE     NUMBER NOT NULL
    ,TITLE    VARCHAR2(30)
    ,DIRECTOR VARCHAR2(30)
    ,RATING   NUMBER
);

CREATE SEQUENCE SEQ_CODE;

CREATE UNIQUE INDEX INDEX_CODE ON TB_MOVIE(CODE);

ALTER TABLE TB_MOVIE
ADD CONSTRAINT PK_CODE PRIMARY KEY (CODE)
USING INDEX INDEX_CODE;

INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '기생충', '봉준호', '4');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '괴물', '봉준호', '4');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '마더', '봉준호', '5');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '살인의추억', '봉준호', '5');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '마더', '봉준호', '5');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '7광구', '김지훈', '1');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '유전', '아리에스터', '5');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '미드소마', '아리에스터', '3');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '위플래쉬', '데미언셔젤', '5');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '라라랜드', '데미언셔젤', '4');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '위플래쉬', '데미언셔젤', '5');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '범죄와의전쟁', '윤종빈', '4');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '군도', '윤종빈', '2');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '용서받지못한자', '윤종빈', '4');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '자전차왕엄복동', '김유성', '1');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '원스', '존카니', '4');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '비긴어게인', '존카니', '3');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '아가씨', '박찬욱', '3');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '올드보이', '박찬욱', '5');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '친절한금자씨', '박찬욱', '4');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '저수지의개들', '쿠엔틴타란티노', '4');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '펄프픽션', '쿠엔틴타란티노', '4');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '헤이트풀8', '쿠엔틴타란티노', '3');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '어느가족', '고레에다히로카즈', '5');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '브로커', '고레에다히로카즈', '2');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '바닷마을다이어리', '고레에다히로카즈', '3');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '추격자', '나홍진', '4');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '곡성', '나홍진', '3');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '황해', '나홍진', '4');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '박하사탕', '이창동', '5');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '버닝', '이창동', '3');
INSERT INTO TB_MOVIE VALUES (SEQ_CODE.NEXTVAL, '타짜', '최동훈', '4');












